In [1]:
import numpy as np

def makeboard():
    return np.array([[None, None, None],[None,None,None],[None,None,None]])
    

In [2]:
newboard = makeboard()
firstboard = makeboard()

In [3]:
firstboard

array([[None, None, None],
       [None, None, None],
       [None, None, None]], dtype=object)

In [34]:
def get_move():
    row = int(input("Which Row do you choose?"))
    column = int(input("Which Column do you choose?"))
    
    if row and column in (1,2,3):
        return row-1,column-1
    else:
        print("You can only choose 1, 2 or 3")
        return get_move()
    
    

In [5]:
get_move()

Which Row do you choose?1
Which Column do you choose?2


(1, 2)

In [32]:
player1 = 0

def make_move(board):
    updateboard = board
    choseplayer = input("'player1' or 'player2'")
    if choseplayer == "player1":
        row, column = get_move()
        #board update with coordinates
        updateboard[row,column] = "X";
    else:
        row, column = get_move()
        updateboard[row,column] = "O";
    print(updateboard)
    return updateboard



In [22]:
def changemoves(board):
    check = any(elem is None for elem in firstboard)
    while check is True:
        make_move(board, input("'player1' or 'player2'"), get_move())
    else:
        return print("board is full")

In [23]:
np.any(firstboard)

'X'

In [ ]:
changemoves(firstboard)

In [ ]:
newboard

In [ ]:
board2 = makeboard()

In [ ]:
board2

In [28]:
def taketurns(board):
    while None in board:
        make_move(board)
    else:
        return "board is full"
    
         

In [35]:
taketurns(newboard)

'player1' or 'player2'player1
Which Row do you choose?3
Which Column do you choose?2
[[None None None]
 [None 'X' 'O']
 [None 'X' None]]
'player1' or 'player2'player1
Which Row do you choose?1
Which Column do you choose?1
[['X' None None]
 [None 'X' 'O']
 [None 'X' None]]
'player1' or 'player2'e
Which Row do you choose?121
Which Column do you choose?ee


ValueError: invalid literal for int() with base 10: 'ee'

In [54]:
winnerlines = np.array([[(0,0),(0,1),(0,2)]
               [(1,0),(1,1),(1,2)],
               [(2,0),(2,1),(2,2)],
               
               [(0,0),(1,0),(2,0)],
               [(0,1),(1,1),(2,1)],
               [(0,2),(1,2),(2,2)],
              
               [(0,0),(1,1),(2,2)],
               [(0,2),(1,1),(2,0)]])

In [55]:
def checkwinner(board):
    for lines in winnerlines:
        if board[lines]

for lines in winnerlines:
    if lines == ["X", "X", "X"]:
        print("Yay")
    else: 
        print("Gay")

SyntaxError: invalid syntax (<ipython-input-55-41ddac27629a>, line 3)

In [61]:
winnerlines[0]

array([[0, 0],
       [0, 1],
       [0, 2]])

In [62]:
newboard[0]

array(['X', None, None], dtype=object)

In [58]:
type(newboard)

numpy.ndarray

In [60]:
type(winnerlines)

numpy.ndarray

In [63]:
winnerlines


array([[[0, 0],
        [0, 1],
        [0, 2]],

       [[1, 0],
        [1, 1],
        [1, 2]],

       [[2, 0],
        [2, 1],
        [2, 2]],

       [[0, 0],
        [1, 0],
        [2, 0]],

       [[0, 1],
        [1, 1],
        [2, 1]],

       [[0, 2],
        [1, 2],
        [2, 2]],

       [[0, 0],
        [1, 1],
        [2, 2]],

       [[0, 2],
        [1, 1],
        [2, 0]]])

In [81]:
firstboard[winnerlines[0][1]]

array([['X', 'X', 'X'],
       ['X', 'X', 'X']], dtype=object)

In [77]:
firstboard[0][1]

'X'

In [67]:
lines[0][1]

2

In [69]:
winnerlines[0][1]

array([0, 1])

In [105]:
random1 = (0,1)
random2 = (0,0)
random3 = (0,2)

In [106]:
type(randoml)

tuple

In [109]:
print(firstboard[random1])
print(firstboard[random2])
print(firstboard[random3])

X
X
X


In [110]:
tuple(winnerlines[0][1])

(0, 1)

In [111]:
firstboard

array([['X', 'X', 'X'],
       ['X', 'X', 'X'],
       ['X', 'X', 'X']], dtype=object)

In [115]:
winnerlines[0][0][0]

0

In [116]:
firstboard[0][1]

'X'

In [117]:
list1 = [(1,0),(0,0),(2,2)]
list2 = [(1,3),(1,2),(3,1)]

list3 = list1 + list2

In [118]:
list3

[(1, 0), (0, 0), (2, 2), (1, 3), (1, 2), (3, 1)]

In [121]:
for line in list3:
        line_values = [list4[x][y] for (x, y) in line]
        if len(set(line_values)) == 1 and line_values[0] is not None:
            print(line_values[0])

TypeError: cannot unpack non-iterable int object

In [120]:
list4 = [[(1,0),(0,0),(2,2)],[(1,3),(1,2),(3,1)]]

In [122]:
type(list4)

list

In [123]:
BOARD_WIDTH = 3
BOARD_HEIGHT = 3

def new_board():
    board = []
    for x in range(0, BOARD_WIDTH):
        column = []
        for y in range(0, BOARD_HEIGHT):
            column.append(None)
        board.append(column)

    return board

In [124]:
list5 = new_board()

In [125]:
list5

[[None, None, None], [None, None, None], [None, None, None]]

In [126]:
type(list5)

list

In [127]:
for line in list5:
        line_values = [list5[x][y] for (x, y) in line]
        if len(set(line_values)) == 1 and line_values[0] is not None:
            print(line_values[0])

TypeError: cannot unpack non-iterable NoneType object

In [128]:
for line in list5:
        line_values = [list5[x][y] for (x, y) in line]
        if len(set(line_values)) == 1 and line_values[0] is not None:
            print(line_values[0])

TypeError: cannot unpack non-iterable NoneType object

In [129]:
def get_winner(board):
    all_line_co_ords = get_all_line_co_ords()

    for line in all_line_co_ords:
        line_values = [board[x][y] for (x, y) in line]
        if len(set(line_values)) == 1 and line_values[0] is not None:
            return line_values[0]

    return None

In [136]:
import random

BOARD_WIDTH = 3
BOARD_HEIGHT = 3

def new_board():
    board = []
    for x in range(0, BOARD_WIDTH):
        column = []
        for y in range(0, BOARD_HEIGHT):
            column.append(None)
        board.append(column)

    return board


def get_winner(board):
    all_line_co_ords = get_all_line_co_ords()

    for line in all_line_co_ords:
        line_values = [board[x][y] for (x, y) in line]
        if len(set(line_values)) == 1 and line_values[0] is not None:
            return line_values[0]

    return None


def get_all_line_co_ords():
    cols = []
    for x in range(0, BOARD_WIDTH):
        col = []
        for y in range(0, BOARD_HEIGHT):
            col.append((x, y))
        cols.append(col)

    rows = []
    for y in range(0, BOARD_HEIGHT):
        row = []
        for x in range(0, BOARD_WIDTH):
            row.append((x, y))
        rows.append(row)

    diagonals = [
        [(0, 0), (1, 1), (2, 2)],
        [(0, 2), (1, 1), (2, 0)]
    ]
    return cols + rows + diagonals

def render(board):
    rows = []
    for y in range(0, BOARD_HEIGHT):
        row = []
        for x in range(0, BOARD_WIDTH):
            row.append(board[x][y])
        rows.append(row)

    row_num = 0
    print ('  0 1 2 ')
    print ('  ------')
    for row in rows:
        output_row = ''
        for sq in row:
            if sq is None:
                output_row += ' '
            else:
                output_row += sq
        print ("%d|%s|" % (row_num, ' '.join(output_row)))
        row_num += 1
    print ('  ------')


def make_move(player, board, move_co_ords):
    if board[move_co_ords[0]][move_co_ords[1]] is not None:
        raise Exception("Illegal move!")

    board[move_co_ords[0]][move_co_ords[1]] = player


def is_board_full(board):
    for col in board:
        for sq in col:
            if sq is None:
                return False
    return True


def play(player1_f, player2_f):
    players = [
        ('X', player1_f),
        ('O', player2_f),
    ]

    turn_number = 0
    board = new_board()
    while True:
        current_player_id, current_player_f = players[turn_number % 2]
        render(board)

        move_co_ords = current_player_f(board, current_player_id)
        make_move(current_player_id, board, move_co_ords)

        winner = get_winner(board)
        if winner is not None:
            render(board)
            print ("THE WINNER IS %s!") % winner
            break

        if is_board_full(board):
            render(board)
            print ("IT'S A DRAW!")
            break

        turn_number += 1

In [142]:
winnerl3 = get_all_line_co_ords()

In [143]:
winnerl2 = [[(0,0),(0,1),(0,2)],
               [(1,0),(1,1),(1,2)],
               [(2,0),(2,1),(2,2)],
               
               [(0,0),(1,0),(2,0)],
               [(0,1),(1,1),(2,1)],
               [(0,2),(1,2),(2,2)],
              
               [(0,0),(1,1),(2,2)],
               [(0,2),(1,1),(2,0)]]

In [145]:
type(winnerl3)

list

In [146]:
winnerl3

[[(0, 0), (0, 1), (0, 2)],
 [(1, 0), (1, 1), (1, 2)],
 [(2, 0), (2, 1), (2, 2)],
 [(0, 0), (1, 0), (2, 0)],
 [(0, 1), (1, 1), (2, 1)],
 [(0, 2), (1, 2), (2, 2)],
 [(0, 0), (1, 1), (2, 2)],
 [(0, 2), (1, 1), (2, 0)]]

In [147]:
winnerl2

[[(0, 0), (0, 1), (0, 2)],
 [(1, 0), (1, 1), (1, 2)],
 [(2, 0), (2, 1), (2, 2)],
 [(0, 0), (1, 0), (2, 0)],
 [(0, 1), (1, 1), (2, 1)],
 [(0, 2), (1, 2), (2, 2)],
 [(0, 0), (1, 1), (2, 2)],
 [(0, 2), (1, 1), (2, 0)]]

In [148]:
def get_winner(board):
    all_line_co_ords = get_all_line_co_ords()

    for line in all_line_co_ords:
        line_values = [board[x][y] for (x, y) in line]
        if len(set(line_values)) == 1 and line_values[0] is not None:
            return line_values[0]

    return None

In [152]:
for line in winnerl3:
    print(line)

[(0, 0), (0, 1), (0, 2)]
[(1, 0), (1, 1), (1, 2)]
[(2, 0), (2, 1), (2, 2)]
[(0, 0), (1, 0), (2, 0)]
[(0, 1), (1, 1), (2, 1)]
[(0, 2), (1, 2), (2, 2)]
[(0, 0), (1, 1), (2, 2)]
[(0, 2), (1, 1), (2, 0)]


In [155]:
list44 = [[(1,0),(0,0),(2,2)],[(1,3),(1,2),(3,1)],[(1,5),(2,0),(6,2)]]

In [175]:
for line in winnerl3:
    for x,y in line:
        lines = list44[x][y]
        print(lines)
        print(set(lines))
        
        if len(set(lines)) == 1 and lines[0] is not None:
            print(lines[0])
            

(1, 0)
{0, 1}
(0, 0)
{0}
0
(2, 2)
{2}
2
(1, 3)
{1, 3}
(1, 2)
{1, 2}
(3, 1)
{1, 3}
(1, 5)
{1, 5}
(2, 0)
{0, 2}
(6, 2)
{2, 6}
(1, 0)
{0, 1}
(1, 3)
{1, 3}
(1, 5)
{1, 5}
(0, 0)
{0}
0
(1, 2)
{1, 2}
(2, 0)
{0, 2}
(2, 2)
{2}
2
(3, 1)
{1, 3}
(6, 2)
{2, 6}
(1, 0)
{0, 1}
(1, 2)
{1, 2}
(6, 2)
{2, 6}
(2, 2)
{2}
2
(1, 2)
{1, 2}
(1, 5)
{1, 5}


In [176]:
list44

[[(1, 0), (0, 0), (2, 2)], [(1, 3), (1, 2), (3, 1)], [(1, 5), (2, 0), (6, 2)]]

In [178]:
list55 = [["X", "O", "X"], ["O", "X", "X"], ["O", "O", "X"]]

In [181]:
for line in winnerl3:
    for x,y in line:
        lines = list55[x][y]

        if len(set(lines)) == 1 and lines[0] is not None:
            print(lines[0])
            

SyntaxError: 'return' outside function (<ipython-input-181-3140d73af47f>, line 8)

In [205]:
def get_winner(board):
    all_line_co_ords = winnerl3

    for line in all_line_co_ords:
        line_values = [board[x][y] for (x, y) in line]
        print(line_values)
        if len(set(line_values)) == 1 and line_values[0] is not None:
            print(set(line_values))
            return line_values[0]

    return None


In [206]:
get_winner(list55)


['X', 'O', 'X']
['O', 'X', 'X']
['O', 'O', 'X']
['X', 'O', 'O']
['O', 'X', 'O']
['X', 'X', 'X']
{'X'}


'X'

In [198]:
for line in winnerl3:
    for x,y in line:
        lines = list55[x][y]
        print(lines)
        #print(set(lines))
        if len(set(lines)) == 1 and lines[0] is not None:
            #print(lines[0])
            continue

X
O
X
O
X
X
O
O
X
X
O
O
O
X
O
X
X
X
X
X
X
X
X
O


In [188]:
list55


[['X', 'O', 'X'], ['O', 'X', 'X'], ['O', 'O', 'X']]

In [193]:
list33 = ["x","x","x"]
list22 = ["x","o","x"]

In [194]:
set(list33)

{'x'}

In [195]:
set(list22)

{'o', 'x'}

In [210]:
line_values = [list55[x][y] for (x, y) in line]
print(line)

[(0, 2), (1, 1), (2, 0)]


In [209]:
line_values

['X', 'X', 'O']

In [224]:
transposed = []
matrix = [[1, 2, 3, 4], [4, 5, 6, 8]]

for i in range(len(matrix[0])):
    transposed_row = []

    for row in matrix:
        transposed_row.append(row[i])
    transposed.append(transposed_row)
    


In [212]:
transpose = [[row[i] for row in matrix] for i in range(2)]

4

In [217]:
def get_winner(board):
    all_line_co_ords = winnerl3

    for line in all_line_co_ords:
        line_values = [board[x][y] for (x, y) in line]
        print(line_values)
        if len(set(line_values)) == 1 and line_values[0] is not None:
            print(set(line_values))
            return line_values[0]

    return None

In [219]:
['X', 'O', 'X']
['O', 'X', 'X']
['O', 'O', 'X']
['X', 'O', 'O']
['O', 'X', 'O']
['X', 'X', 'X']

['X', 'X', 'X']

In [242]:
for line in winnerl3:
    lines = []

    for x,y in line:
        lines.append(list55[x][y])  
        #print(set(lines))
    if len(set(lines)) == 1 and lines[0] is not None:
        print(lines[0])
        print(set(lines))
            

X
{'X'}
X
{'X'}


In [222]:
winnerl3

[[(0, 0), (0, 1), (0, 2)],
 [(1, 0), (1, 1), (1, 2)],
 [(2, 0), (2, 1), (2, 2)],
 [(0, 0), (1, 0), (2, 0)],
 [(0, 1), (1, 1), (2, 1)],
 [(0, 2), (1, 2), (2, 2)],
 [(0, 0), (1, 1), (2, 2)],
 [(0, 2), (1, 1), (2, 0)]]